2020-11-05 19:07:30 [scrapy.utils.log] INFO: Scrapy 2.4.0 started (bot: first_scrapy)
2020-11-05 19:07:30 [scrapy.utils.log] INFO: Versions: lxml 4.6.1.0, libxml2 2.9.5, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1h  22 Sep 2020), cryptography 3.2.1, Platform Windows-10-10.0.18362-SP0
2020-11-05 19:07:30 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2020-11-05 19:07:30 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'first_scrapy',
 'LOG_FILE': 'logs\\first_scrapy\\dytt\\149ab7ae1f5711eb86a8c0b5d793072e.log',
 'NEWSPIDER_MODULE': 'first_scrapy.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['first_scrapy.spiders']}
2020-11-05 19:07:30 [scrapy.extensions.telnet] INFO: Telnet Password: d58a271b7fd7842c
2020-11-05 19:07:31 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2020-11-05 19:07:31 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-11-05 19:07:31 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-11-05 19:07:31 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2020-11-05 19:07:31 [scrapy.core.engine] INFO: Spider opened
2020-11-05 19:07:31 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-11-05 19:07:31 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-11-05 19:07:32 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/robots.txt> (referer: None)
2020-11-05 19:07:32 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (meta refresh) to <GET https://www.dytt8.net/index.htm> from <GET https://www.dytt8.net/>
2020-11-05 19:07:32 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/index.htm> (referer: None)
2020-11-05 19:07:32 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201105/60693.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201105/60693.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201105/60693.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201101/60673.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201103/60682.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201101/60673.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201101/60673.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:33 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201103/60682.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201103/60682.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201104/60690.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201104/60690.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201104/60690.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201104/60691.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201104/60691.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201104/60691.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201029/60661.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201104/60689.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201029/60661.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201029/60661.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:33 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201104/60689.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201104/60689.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201031/60664.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201105/60694.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201026/60650.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201029/60660.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:34 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201031/60664.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201031/60664.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:34 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201105/60694.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201105/60694.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:34 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201026/60650.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201026/60650.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:34 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201029/60660.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201029/60660.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:34 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201027/60653.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:34 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201031/60665.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:34 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201027/60653.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201027/60653.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:34 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201031/60665.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201031/60665.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:34 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201028/60657.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:34 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201028/60657.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201028/60657.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:34 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.dytt8.net/html/gndy/dyzz/20201105/60692.html> (referer: https://www.dytt8.net/index.htm)
2020-11-05 19:07:34 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.dytt8.net/html/gndy/dyzz/20201105/60692.html> (referer: https://www.dytt8.net/index.htm)
Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <200 https://www.dytt8.net/html/gndy/dyzz/20201105/60692.html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\install\python\lib\site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
    result = f(*args, **kw)
  File "d:\install\python\lib\site-packages\scrapy\core\spidermw.py", line 58, in process_spider_input
    return scrape_func(response, request, spider)
  File "d:\install\python\lib\site-packages\scrapy\core\scraper.py", line 149, in call_spider
    warn_on_generator_with_return_value(spider, callback)
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 245, in warn_on_generator_with_return_value
    if is_generator_with_return_value(callable):
  File "d:\install\python\lib\site-packages\scrapy\utils\misc.py", line 230, in is_generator_with_return_value
    tree = ast.parse(dedent(inspect.getsource(callable)))
  File "d:\install\python\lib\inspect.py", line 965, in getsource
    lines, lnum = getsourcelines(object)
  File "d:\install\python\lib\inspect.py", line 952, in getsourcelines
    lines, lnum = findsource(object)
  File "d:\install\python\lib\inspect.py", line 779, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "d:\install\python\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "d:\install\python\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "d:\install\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 21: invalid start byte
2020-11-05 19:07:34 [scrapy.core.engine] INFO: Closing spider (finished)
2020-11-05 19:07:34 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 5065,
 'downloader/request_count': 18,
 'downloader/request_method_count/GET': 18,
 'downloader/response_bytes': 100907,
 'downloader/response_count': 18,
 'downloader/response_status_count/200': 18,
 'elapsed_time_seconds': 3.742142,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 11, 5, 11, 7, 34, 833482),
 'log_count/DEBUG': 18,
 'log_count/ERROR': 15,
 'log_count/INFO': 10,
 'request_depth_max': 1,
 'response_received_count': 17,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 17,
 'scheduler/dequeued/memory': 17,
 'scheduler/enqueued': 17,
 'scheduler/enqueued/memory': 17,
 'spider_exceptions/UnicodeDecodeError': 15,
 'start_time': datetime.datetime(2020, 11, 5, 11, 7, 31, 91340)}
2020-11-05 19:07:34 [scrapy.core.engine] INFO: Spider closed (finished)
